### ISSUE TITLE
maxBuffer

### ISSUE THREAD

**Issue by erwanjegouzo** [wecodemore/grunt-githooks#23]
When the buffer exceeds the default ```exec``` configuration, the process is killed and prevents the code to be committed.
http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
To fix this, we need a way to extend the default exec options with new ones.
Would you consider a PR for that?

**Comment by jshemas** [comment]
Running into the same problem. =/

Looks like all you have to to is set the maxBuffer option higher.
http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

**Comment by franz-josef-kaiser** [comment]
Closing this now as this just means that a task should be split into two tasks if the buffer runs over.
