### ISSUE TITLE
Does not work when .git is not a directory

### ISSUE THREAD

**Issue by wszostak** [wecodemore/grunt-githooks#25]
It is possible in Git that `.git` is not a directory but regular file.

When I create such a file with content:

     gitdir: /path/to/bare/repository/.git

, Git knows that its files are in different path. 

grunt-githooks, however, does not follow this link and returns error:

    Warning: Unable to create directory "/home/wszostak/projekty/NMS/nms/.git/hooks" (Error code: ENOTDIR). Use --force to continue.

**Comment by franz-josef-kaiser** [comment]
Closing as the needed info is missing since more than a year now.
