### ISSUE TITLE
0.3.2 not on npm?

### ISSUE THREAD

**Issue by Narretz** [wecodemore/grunt-githooks#32]
I just tried to update grunt-githooks to 0.3.2, but npm still lists the last version as 0.3.1: https://www.npmjs.org/package/grunt-githooks

Any idea what might be wrong here?

**Comment by franz-josef-kaiser** [comment]
I once again contacted the npm staff. Let's see what happens.

**Comment by andyburke** [comment]
+1

**Comment by amitrai99** [comment]
Still stuck at 0.3.1...

**Comment by franz-josef-kaiser** [comment]
Ok, I tried it a third time. If that doesn't work, I'll simply open a new repo on npm as it can't stay this way.
See Twitter: https://twitter.com/unserkaiser/status/572647508666671104

**Comment by karol-f** [comment]
Any updates on this? Do we have separate repo on npm or is this resolved other way?

**Comment by franz-josef-kaiser** [comment]
@karol-f No, this is not resolved. Please ping them on Twitter as they did not respond to _anything_ by now. Needs peer pressure.

**Comment by karol-f** [comment]
@franz-josef-kaiser Can we solve it somehow on our end? Creating new repo (different name) is an option?

Is there something else you can do?

**Comment by franz-josef-kaiser** [comment]
> Creating new repo (different name) is an option?

Look at the _stars_ on this repo: No, this is not an option just because one company does not respond to a single mans request. Better be a community and offer help by using group pressure on public/social media streams.

**Comment by karol-f** [comment]
So, if possible, please at least add README info that setting in package.json new repo is possible

package.json
```javascript
{
  "dependencies": {
    "grunt-githooks": "https://github.com/wecodemore/grunt-githooks.git"
  }
}
```

Regards!

**Comment by franz-josef-kaiser** [comment]
@karol-f PR welcome :)

**Comment by franz-josef-kaiser** [comment]
see #42

**Comment by mischah** [comment]
mhmm. Just recognized that version 0.4.0 isn’t published on npm.
According to [npmjs.com](https://www.npmjs.com/package/grunt-githooks/access) you have access to the package.

Are there technical issues since the transfer from rhumarics account to wecodemore?
What happens if you try to `npm publish` the latest version?

**Comment by franz-josef-kaiser** [comment]
@mischah I tried that previously, but it didn't go through, hence I contacted NPM via Twitter and asked for help with peer pressure in this thread. I now tried it again and it worked :)

**Comment by mischah** [comment]
Woop. It’s available via npm :ok_hand:
