### ISSUE TITLE
Question: How can I see output from grunt tasks

### ISSUE THREAD

**Issue by james-gardner** [wecodemore/grunt-githooks#34]
Hi,

I'm a bit of a bash newbie and I was wondering how easy it would be to be able to see the output of my grunt tasks as they are run during the pre-commit phase?

At the moment it only displays the output from my tasks when they have all finished.

Any help appreciated.

**Comment by franz-josef-kaiser** [comment]
See v0.4.0 and https://github.com/wecodemore/grunt-githooks/pull/36
