### ISSUE TITLE
Node.js pre commit template script

### ISSUE THREAD

**Issue by scottmcpherson** [wecodemore/grunt-githooks#38]
Hey guys,

Is it possible to execute the node.js.hb template?

I tried setting the template to that file and it doesn't seem to be getting executed. 

```
githooks: {
      options: {
        template: './node_modules/grunt-githooks/templates/node.js.hb',
      }
      ...
```

**Comment by franz-josef-kaiser** [comment]
@scottmcpherson Sorry for getting back to this issue that late. Have you solved the issue or do still need help?
