### ISSUE TITLE
0.4.0 not on npm

### ISSUE THREAD

**Issue by mjschranz** [wecodemore/grunt-githooks#42]
Minor issue since one can just link to the tag directly but this would be highly preferable!

Thanks!

**Comment by franz-josef-kaiser** [comment]
Please stick with the first issue. PR as suggested welcome there. Pinging npm on Twitter, etc. as well.

**Comment by mjschranz** [comment]
Like I said, I know how to get around it. I can't actually do anything to get it on npm though as I am obviously not an owner of the repo and don't have access rights.

**Comment by franz-josef-kaiser** [comment]
As long as npm does not responde, I, as owner, have no chance to fix that.

**Comment by mischah** [comment]
@mjschranz  It’s now on npm :ok_hand: 

… see https://github.com/wecodemore/grunt-githooks/issues/32#issuecomment-157441317

**Comment by mjschranz** [comment]
Yay! :+1:
