### ISSUE TITLE
option to log output to screen

### ISSUE THREAD

**Issue by dorgan** [wecodemore/grunt-githooks#43]
Currently my pre-commit githook runs a grunt task, but I dont see a way to have the output logged to the screen.

**Comment by franz-josef-kaiser** [comment]
@dorgan have you tried printing to the CLI? It's hard to suggest something with that little information and no code.

**Comment by dorgan** [comment]
@franz-josef-kaiser printing how??  Not if I run the grunt task on its own, i see the output, but running the grunt task inside the githook, looks like it holds all the output until it completes.

**Comment by kurdin** [comment]
>looks like it holds all the output until it completes
I see the same result and its not very UX friendly specially for large tasks

**Comment by franz-josef-kaiser** [comment]
The templates are just _recommendations_ and should serve as "how to" and are not meant to be used as is. If it's just about that, then please adjust them to your needs. You could write a hook in pretty much every language that your environment offers and we can't add and maintain one "perfect"-does-it-all script in every major language.
