### ISSUE TITLE
Update Handlebars

### ISSUE THREAD

**Issue by jshemas** [wecodemore/grunt-githooks#64]
Its looks like this project is using a very old version of Handlebars, would it be possible to update this?

**Comment by franz-josef-kaiser** [comment]
Hi @jshemas – I have edited both the title as well as the content (not that it would not be visible anymore). Could you please for future issues like this one, start by contacting us via email and give us time to fix things **before** you go public with this? This is the default behavior when you find such an issue. Thanks.

**Comment by jshemas** [comment]
Hey there,

Yeah, this isn't really a threat I would be worried about. But it would be awesome if you updated regardless.

Thanks!

**Comment by franz-josef-kaiser** [comment]
Sure. I already assigned a milestone.
