### ISSUE TITLE
Git pre-push with a lot of operation go to timeout

### ISSUE THREAD

**Issue by ricByte** [wecodemore/grunt-githooks#66]
Hi, 

i use this plugin to run tests before push to the GitHub repository. I have some task like jshint and clean too. 
When i try to push something git open the connection with GItHub and then run all commands(tests, jshint, etc...). So with all of that operations the connection go timeout and i can't push. 
I don't know how you can reproduce it.
You know why? There are some tricks to prevent that?

regards
Riccardo

**Comment by franz-josef-kaiser** [comment]
@ricByte You probably have to find a way to split your files. Another way around it might be to use a CI service like _CircleCI_, _TravisCI_ or _CodeShip_, who have stronger machines than you have. But this also means using different hooks so it will run before merging or in other cases.
