### ISSUE TITLE
See if it's possible to keep pretty formatting in hook output

### ISSUE THREAD

**Issue by rhumaric** [wecodemore/grunt-githooks#9]
At least in Windows, as noticed by @andrewjmead in #6:

Grunt output:
<img src="https://f.cloud.github.com/assets/2992789/1303259/c33b93b4-314d-11e3-8996-8d0aeed0bb86.PNG" alt="Grunt output with pretty formatting">

Hook output:

<img src="https://f.cloud.github.com/assets/2992789/1303260/cbad024e-314d-11e3-8065-7e88b1439769.PNG" alt="Hook output, lost colors and line breaks">

It would be nice if Grunt pretty output was kept when run inside hooks

 - [ ] Check what's happening on other platforms
 - [ ] Identify what breaks the formatting
 - [ ] Fix it if possible!

**Comment by franz-josef-kaiser** [comment]
@F1LT3R Sure. Do you want to work on an ASCII-only patch?
